### PR TITLE
fix(): fix ticket 54

### PR DESCRIPTION
**Pull request by Fdom92**
This PR fix the ticket #54 re setting the error code when going back to dashboard. There is another thing on the issue that would need an answer, do we should show that the link is invalid before going to the enter access code page? In that case, should we show an error message or an alert saying that session link is invalid @Wholloran

### CODE REVIEW

**Comment by Wholloran** [comment]
How do our error states look throughout the rest of the app? have we been using error messages or alerts? I'm ok with doing either I just want to keep error format uniform throughout the app. I don't remember the style we have done in other places off hand so let me test and I'll provide another update. @Fdom92 @PaulPaulDevelops

**Comment by PaulPaulDevelops** [comment]
@Wholloran 

As far as error states, we have only implemented a few. I want to discuss with Rachel a uniform style for errors as it was not depicted in the original designs.

We should make a task to review through, identify where and what needs an error state and then style it accordingly once we agree on a uniform style.

Currently, I have any error text being the primary orange color, I don't believe this is informative and noticeable to the user as it looks like regular text.

**Comment by PaulPaulDevelops** [comment]
@Fdom92 I discussed with Rachel and we should move forward with putting this error within an alert with information about the error. I believe we already have alert functionality within the project already.

**Comment by Fdom92** [comment]
@PaulPaulDevelops added a simple alert with the error coming from the backend instead of displaying it on the page.

**Pull request merged**
