### PR TITLE
fix(): fix ticket 65

### PR DESCRIPTION
**Pull request by Fdom92**
This PR fix the issue #65 redirecting to dashboard after removing the connection.

### CODE REVIEW

**Comment by PaulPaulDevelops** [comment]
Hey @Fdom92 !

I tested this out on the branch and ran into an error after selecting to delete a connection. Please see the screenshot down below and advise :)

Thanks!

screen shot 2018-08-08 at 7 58 41 pm

**Comment by Fdom92** [comment]
@PaulPaulDevelops fixed, let me know if still having issues

**Comment by PaulPaulDevelops** [comment]
Hey! Thanks for the change. Is there any way we can add the smooth navigation transition in? I feel like it awkwardly flashes into the settings page.

I'm starting to think it might be a good idea to add a confirmation popup too just in case a user accidentally hits delete. What do you think? @Wholloran ?

**Comment by Wholloran** [comment]
@PaulPaulDevelops Yes I agree, we should do a confirmation popup.

**Pull request merged**
